### ISSUE TITLE
Google App Engine example doesn't work with Mozilla Firefox

### ISSUE THREAD

**Issue by ciromoraismedeiros** [pythonforfacebook/facebook-sdk#100]
Hi

I'm beginner on developing apps on GAE and started with a simple app that uses facebook login. Got your code example (for facebook login on GAE) and discovered it doesn't work fine with Mozilla Firefox.

Here is my app: ciro-app-id.appspot.com

When the user logs in with the facebook account, Firefox starts some kind of infinite requests loop.
This log has been taken from GAE logs and repeats itself for each request made by Firefox:
2013-10-22 19:14:42.364 / 200 109ms 1kb Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
186.226.15.243 - - [22/Oct/2013:19:14:42 -0700] "GET / HTTP/1.1" 200 1303 - "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)" "ciro-app-id.appspot.com" ms=109 cpu_ms=70 cpm_usd=0.000146 app_engine_release=1.8.6 instance=00c61b117c5ef2a696a0544fcffd207dae4362

In other browsers, the code works perfectly.

What can you tell me to do?

**Comment by martey** [comment]
Unassigning myself since it is pretty clear that I am not going to get a chance to look at this anything soon.
