### ISSUE TITLE
Update Documentation and Examples for Graph API v2.0

### ISSUE THREAD

**Issue by vpong** [pythonforfacebook/facebook-sdk#149]
The main example for using get_connections is

friends = g.get_connections("me", "friends")

As explained in http://stackoverflow.com/questions/23435961/fetching-list-of-friends-using-facebook-2-0, this doesn't work the way I be most people think it would. Facebook has up'ed their privacy settings for apps. I think updating this exampling to

friends = g.get_connections("me", "taggable_friends")

would help.

**Comment by tvmanikandan** [comment]
I am trying to get posts of mine and my friends. But the list is empty. I am able to get the posts of Mr. Bill Gates as given in the example. Please clarify what is missing from my side.

API call : 
posts = graph.get_connections(profile['id'], 'posts')

-Mani

**Comment by vpong** [comment]
tvmanikandan, that might be a question that's better suited for stackoverflow, since it doesn't relate directly to this issue (updating the documentation).

One reason you may only be getting their posts is that you don't have permission to see you're friends' posts, and you're only allowed to see public posts. If you're trying to get things from your feed, this [stackoverflow questions might help](http://stackoverflow.com/questions/1059640/facebook-offline-access-step-by-step/3249758#3249758--I).

**Comment by martey** [comment]
This should be fixed - we have better documentation (mostly thanks to @mylsb) and it should be updated for v2.*.

If you run across an example in the documentation that does not work, please open a new issue.
