### ISSUE TITLE
i get error when post image into my page

### ISSUE THREAD

**Issue by hongquantq92** [pythonforfacebook/facebook-sdk#177]
error is facebook.GraphAPIError: (#100) Parameters do not match any fields that can be updated.
i try post status very good but image not working and error .
my code : 
tags = json.dumps([{'x':50, 'y':50, 'tag_uid':12345}, {'x':10, 'y':60, 'tag_text':'a turtle'}]) a=graph.put_photo(open("test.jpg", 'rb'), 'Look at this cool photo!', '1401275423450058', tags=tags )

**Comment by kyouko-taiga** [comment]
Hi, I encountered the same issue, using the version 1.0.0-alpha of the SDK.
I tried both version 1.0 and 2.2 of the Facebook API.

**Comment by martey** [comment]
The problem is with the example. I am working on improving the documentation.
