### ISSUE TITLE
PyPI package not up-to-date

### ISSUE THREAD

**Issue by kyouko-taiga** [pythonforfacebook/facebook-sdk#190]
Hi mates,
I'd like to report that the package on PyPI doesn't seem up-to-date. At least I couldn't get it to work with python 3.4, while installing facebook-sdk directly from the github repository was successful.

Thanks for your work.

**Comment by sfrdmn** [comment]
It isn't up to date because there hasn't been a release yet.

See: https://groups.google.com/forum/#!topic/pythonforfacebook/Xxj1u22yNXU

**Comment by kyouko-taiga** [comment]
I see, sorry for bothering.
