### ISSUE TITLE
put_photo creating UnicodeDecodeError 

### ISSUE THREAD

**Issue by rajasimon** [pythonforfacebook/facebook-sdk#191]
every photo i upload using put_photo causing this issue. How to get rid of this ?

Full Traceback

>Environment:

>Request Method: GET
Request URL: http://localhost:8000/facebook/signal

>Django Version: 1.7
Python Version: 2.7.6
Installed Applications:
('django.contrib.sites',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'frontend',
 'twitter_api',
 'facebook_api',
 'sorl.thumbnail')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

>Traceback:
File "/home/vijay/nightybuild/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/vijay/nightybuild/panaface/facebook_api/views.py" in facebook_signal
  81. 	graph.put_photo(open(fromDatabaseImage), 'Look at this cool photo!', None, tags=tags)
File "/home/vijay/nightybuild/env/local/lib/python2.7/site-packages/facebook.py" in put_photo
  213.         content_type, body = self._encode_multipart_form(post_args)
File "/home/vijay/nightybuild/env/local/lib/python2.7/site-packages/facebook.py" in _encode_multipart_form
  273.         body = CRLF.join(L)

>Exception Type: UnicodeDecodeError at /facebook/signal
Exception Value: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

**Comment by martey** [comment]
This looks like a duplicate of #43. Can you try using git master (instead of 0.4.0) and see if that fixes your issue?

**Comment by martey** [comment]
I am closing this. Please comment on #43 if git master does not fix your issue.
