### ISSUE TITLE
Current version support and new pypi version

### ISSUE THREAD

**Issue by tino** [pythonforfacebook/facebook-sdk#192]
What is the current status on API version support? Is 2.2 fully supported? 

If so, it would be great to release a new version on pypi! And maybe a little support section in the docs?

**Comment by martey** [comment]
I think both of these questions (which Graph API versions are supported, and when the next version is going to be released) have already been answered in [the Google Group](https://groups.google.com/forum/#!forum/pythonforfacebook).

**Comment by tino** [comment]
Ah, allright, missed the link to the Google Groups
