### ISSUE TITLE
Can't specify 'id' as a keyword argument in get_object()

### ISSUE THREAD

**Issue by mmadurski** [pythonforfacebook/facebook-sdk#197]
Since `id` is being used as a positional argument name in `get_object()`, we cannot pass `id` as a keyword argument, which, can be necessary for certain graph queries.

Doing something like the following:
```
graph.get_object('comments', id='https://example.com')
```
will result in: 
```
TypeError: get_object() got multiple values for keyword argument 'id'
```

**Comment by mmadurski** [comment]
https://github.com/pythonforfacebook/facebook-sdk/pull/198

**Comment by martey** [comment]
Closing; will discuss this on the pull request.
