### ISSUE TITLE
Pip version is way out of date

### ISSUE THREAD

**Issue by litchfield** [pythonforfacebook/facebook-sdk#207]
Doesn't even support the version= parameter in the docs

**Comment by martey** [comment]
Please search before opening new issues. This is a duplicate of #192.

**Comment by litchfield** [comment]
Dude. This issue isn’t solved….. the pip version is still out of date….. and I can’t find your group post (nor do I care about it)…… how about you just update it?


Simon Litchfield
+61-416-027-826
