### ISSUE TITLE
parse_signed_request and Python 3

### ISSUE THREAD

**Issue by stianpr** [pythonforfacebook/facebook-sdk#208]
Using Python 3 and `facebook.parse_signed_request` explicitly does not work. `base64.urlsafe_b64decode` returns a byte-string on line 402 and `json.loads` on line 411 does not handle byte-strings. You'll get this exception:

```
  File ".../venv/src/facebook-sdk-master/facebook/__init__.py", line 411, in parse_signed_request
    data = json.loads(data)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```
I cannot understand that anyone can use this in a Python 3 environment...

In order to fix this we need tests for the `parse_signed_request` function and verify that this bug exist and create a version that works for both Python 2 and 3.

**Comment by stianpr** [comment]
@martey Would it be possible to get access to the Facebook App used for testing (ID: 198798870326423)? I can then create a cookie which I can use in the tests for this bug fix.

**Comment by stianpr** [comment]
Is it possible to get any feedback on this?

**Comment by martey** [comment]
I looked at your pull request and it seems fine. It might take me a few days to change the cookie value in the new test, but I think you should be able to use the environmental variables in https://github.com/pythonforfacebook/facebook-sdk/blob/master/.travis.yml to do so.

**Comment by martey** [comment]
See #209 and d9c670568784d1091b257b94497a22fbcf2617b8.
