### ISSUE TITLE
Issue installing facebook SDK

### ISSUE THREAD

**Issue by baggarwal27** [pythonforfacebook/facebook-sdk#211]
Warning (from warnings module):
  File "C:\Python34\lib\site-packages\setuptools\dist.py", line 283
    self.metadata.version,
UserWarning: The version specified requires normalization, consider using '1.0.0a0' instead of '1.0.0-alpha'.

**Comment by martey** [comment]
Is this preventing the installation from succeeding?

Based on the comments in https://bitbucket.org/pypa/setuptools/pull-request/118/remove-warning-on-normalization/diff and [PEP 440](https://www.python.org/dev/peps/pep-0440/), I don't think is a serious issue, but if this (despite being called a warning) is preventing you from installing the package, we can definitely change the versioning scheme.

**Comment by baggarwal27** [comment]
Yeah. It stops after this message. When I write a script with import
facebook it says no module name requests.

Am new to python. Please suggest

**Comment by martey** [comment]
Can you run `python --version` and `pip --version` and also tell me what command you are using to install the library?

**Comment by baggarwal27** [comment]
I was able to install it. But still error while importing facebook

Traceback (most recent call last):
  File "C:/Python34/Scripts/Facebook_1.py", line 1, in <module>
    import facebook
  File "C:\Python34\lib\site-packages\facebook.py", line 222
    except urllib2.HTTPError, e:
                            ^
SyntaxError: invalid syntax

**Comment by martey** [comment]
Your original error looks like you were installing from git (which is what you want to do), but the traceback you listed is from version 0.4.0 (which is not compatible with Python 3.4 or any current versions of the Graph API).

Can you give the *original* commands you used to try and install it?

**Comment by baggarwal27** [comment]
I am sorry for the confusion. I am new to python.I did so many things and
finally I don't remember what I did when I sent you email last time.
I want to create a application where I can access users information from
facebook (if users authorize) and do some programming based on their data.
My windows version is 7, 64 bit system. Please let me know what all I
should install for my requirement.

Also I would use the same feature with Twitter as well. Please let me know
what version and tool is compatible will all of these.

**Comment by baggarwal27** [comment]
I removed this version and installed 2.7.9 and facebook seems to be working
fine as of now. You rock dude.
