### ISSUE TITLE
App secret in GraphAPI constructor

### ISSUE THREAD

**Issue by dimitrovskif** [pythonforfacebook/facebook-sdk#212]
If the Facebook app has `Require App Secret` enabled, this SDK becomes useless - all requests are going to fail.

There should be an option for providing a secret key in the `GraphAPI(**kwargs)` constructor

**Comment by dimitrovskif** [comment]
This is my proposal. https://github.com/pythonforfacebook/facebook-sdk/pull/213

**Comment by martey** [comment]
Closing because #213 seems like a good solution to this issue. Further discussion should take place there.
