### ISSUE TITLE
Need to enable billing account to use with App Engine

### ISSUE THREAD

**Issue by MeLight** [pythonforfacebook/facebook-sdk#215]
Getting this error if using the lib on an app without a billing account on Google App Engine

`FeatureNotEnabledError: The Socket API will be enabled for this application once billing has been enabled in the admin console.`

**Comment by MeLight** [comment]
Getting this error if using the lib on an app without a billing account on Google App Engine
FeatureNotEnabledError: The Socket API will be enabled for this application once billing has been enabled in the admin console.

**Comment by chrisrote** [comment]
According to GAE Docs, you must have a paid account to enable the sockets, once enabled:
"You can run and test code using sockets on the development server, without using any special command line parameters."

@MeLight I believe that they are dropping support for GAE in this package moving forward.  But yeah this should be added to documentation.

I have had a few issues with GAE, see https://github.com/pythonforfacebook/facebook-sdk/issues/214 for some of the info I have learned as well :)

**Comment by chrisrote** [comment]
Just a note here for future GAE users, I ran into the same issue. I would recommend using https://github.com/crhym3/simpleauth I found Simple Auth and made some adjustments to get my app up and running. There are definitely improvements to be made, but it should get you to a good starting place.
