### ISSUE TITLE
facebook.py __init__ not supporting version

### ISSUE THREAD

**Issue by ChristianVersloot** [pythonforfacebook/facebook-sdk#216]
I installed the python for Facebook class using pip install facebook-sdk. I then used the example from your documentation to start working with it:

```
import facebook

graph = facebook.GraphAPI(access_token='your_token', version='2.2')
```

However, I am getting a TypeError:

```
TypeError: __init__() got an unexpected keyword argument 'version'
```

This problem is caused due to the fact that in facebook.py that was installed, in method GraphAPI, no version argument is present. This is contrary to what is supported according to your documentation.

**Comment by martey** [comment]
`pip install facebook-sdk` installs version 0.4.0, but the documentation example you are using is for git master. Try installing with `pip install git+https://github.com/pythonforfacebook/facebook-sdk@e4f7b25fd5#egg=facebook`.
