### ISSUE TITLE
GraphAPI constructor choking on version parameter

### ISSUE THREAD

**Issue by bllfrnch** [pythonforfacebook/facebook-sdk#224]
This code works fine:

`fb_graph = facebook.GraphAPI(access_token=oauth.get_access_token())`

But this code gives an error:

`fb_graph = facebook.GraphAPI(access_token=oauth.get_access_token(), version='2.3')`

`TypeError: __init__() got an unexpected keyword argument 'version'`

Did I find a bug or have I made a mistake somewhere? Thanks for doing what you do.

**Comment by bllfrnch** [comment]
Also... I'm very new to Python and have been continually surprised by the syntax. Hopefully you'll forgive my ignorance.

**Comment by martey** [comment]
Can you verify that you installed facebook-sdk from Git (https://github.com/pythonforfacebook/facebook-sdk/blob/master/docs/install.rst#installing-from-git)?

Version 0.4.0 only supports v1.0 of the Graph API, which is no longer available, so you definitely want to be using a recent Git checkout.

**Comment by bllfrnch** [comment]
Hey, thanks for your reply. That was the problem, I've got a more recent version installed and all's working as expected.
