### ISSUE TITLE
The code doesn't work on google app engine

### ISSUE THREAD

**Issue by n5agarwa** [pythonforfacebook/facebook-sdk#228]
Hi,

I tried running this code for google app engine. But it doesn't go to index.html once it's authorized from facebook. The callback url brings it back to "/" showing login page even though user is logged in.

**Comment by martey** [comment]
If you are using the Google App Example code that was previously included in this project, please note that it has been removed (see "[Google App Engine support](https://groups.google.com/forum/#!topic/pythonforfacebook/6gqfN5xFcEU)" for more details).

If you need help getting this project working with Google App Engine, your best bet is to post to the [Google Group](https://groups.google.com/forum/#!forum/pythonforfacebook). If you do so, you should include more details about your environment (including what version of the SDK you are running).

**Comment by chrisrote** [comment]
Just a note here for future GAE users, I ran into the same issue. I would recommend using https://github.com/crhym3/simpleauth I found Simple Auth and made some adjustments to get my app up and running. There are definitely improvements to be made, but it should get you to a good starting place.

**Comment by n5agarwa** [comment]
Thanks @martey  and @chrisrote. 

I actually need it for flask + facebook. I think I may get something using oauth and then should convert it to run on GAE. Although, working on GAE is a pain.
