### ISSUE TITLE
Syntax error using python 3.4.3

### ISSUE THREAD

**Issue by sgzsh269** [pythonforfacebook/facebook-sdk#229]
Getting the following error when I `import facebook` using python 3.4.3
```
facebook.py", line 222
    except urllib2.HTTPError, e:
                            ^
SyntaxError: invalid syntax
```
Believe it's a compatibility issue with python 3.4.3. 
After running it through `2to3` tool, it seems to work.

**Comment by martey** [comment]
Closing because this isn't an issue with current master and this is a duplicate (please search the issues before creating a new one). See #148.
