### ISSUE TITLE
Make library compatible with Python 3.

### ISSUE THREAD

**Issue by skorokithakis** [pythonforfacebook/facebook-sdk#230]
I'm trying to use this library with a Python 3 project but it doesn't work. The first thing that fails is this:

```
  File "/var/projects/env/lib/python3.4/site-packages/facebook.py", line 222
    except urllib2.HTTPError, e:
```

**Comment by lucasrangit** [comment]
@skorokithakis that's a bug in the old version of the SDK. can you try the new version on Github?

**Comment by skorokithakis** [comment]
Sure, I'll try that and report back, thanks.

**Comment by martey** [comment]
See #148 or #162.
