### ISSUE TITLE
Update a PyPi package?

### ISSUE THREAD

**Issue by wannaphongcom** [pythonforfacebook/facebook-sdk#231]
Today, Facebook-sdk support python 3, but facebook-sdk (PyPi) is old. Not update. Do you have any plans to update a PyPi package?
https://pypi.python.org/pypi/facebook-sdk
Thank you.

**Comment by martey** [comment]
See #192 and https://groups.google.com/forum/#!topic/pythonforfacebook/Xxj1u22yNXU.
