### ISSUE TITLE
Error while importing module

### ISSUE THREAD

**Issue by arvindpdmn** [pythonforfacebook/facebook-sdk#234]
I must be doing something horribly wrong but I cannot import the module in Python3. The documentation says it is supported in Python3.

```
Traceback (most recent call last):
  File "fb.py", line 1, in <module>
    import facebook
  File "/usr/local/lib/python3.4/dist-packages/facebook.py", line 222
    except urllib2.HTTPError, e:
                            ^
SyntaxError: invalid syntax
```

**Comment by martey** [comment]
You're using documentation for git master while installing a version (0.4.0) from several years ago that doesn't support Python 3.

**Comment by arvindpdmn** [comment]
Interpreting your reply this way: I am using an old version but documentation on readthedocs.org is up-to-date.

So I uninstalled facebook-sdk and reinstalled. Looks like pip is not getting anything more recent than 0.4.0. Documentation does not say which is the latest version. Should I therefore download from GitHub and try a manual install?

```
sudo pip install facebook-sdk
Downloading/unpacking facebook-sdk
  Downloading facebook-sdk-0.4.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/facebook-sdk/setup.py) egg_info for package facebook-sdk
    
Installing collected packages: facebook-sdk
  Running setup.py install for facebook-sdk
      File "/usr/local/lib/python3.4/dist-packages/facebook.py", line 222
        except urllib2.HTTPError, e:
                                ^
    SyntaxError: invalid syntax
    
    
Successfully installed facebook-sdk
Cleaning up...
```

**Comment by arvindpdmn** [comment]
Got it: `sudo python setup.py install`

Version:
facebook-sdk==1.0.0-alpha
