### ISSUE TITLE
GraphAPIError: An active access token must be used to query information about the current user.

### ISSUE THREAD

**Issue by holms** [pythonforfacebook/facebook-sdk#236]
I get a token I go here: https://developers.facebook.com/tools/access_token/

```
token = "mytoken"
graph = facebook.GraphAPI(access_token=token, version='2.4')

profile = graph.get_object("me")
---------------------------------------------------------------------------
GraphAPIError                             Traceback (most recent call last)
<ipython-input-26-f393712ff5fc> in <module>()
----> 1 profile = graph.get_object("me")

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/facebook/__init__.pyc in get_object(self, id, **args)
    102     def get_object(self, id, **args):
    103         """Fetchs the given object from the graph."""
--> 104         return self.request(self.version + "/" + id, args)
    105
    106     def get_objects(self, ids, **args):

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/facebook/__init__.pyc in request(self, path, args, post_args, files, method)
    269
    270         if result and isinstance(result, dict) and result.get("error"):
--> 271             raise GraphAPIError(result)
    272         return result
    273

GraphAPIError: An active access token must be used to query information about the current user.
```

What's going on? The same goes basically to any query

**Comment by lucasrangit** [comment]
First, this type of question should be posted to the forum at https://groups.google.com/forum/#!forum/pythonforfacebook .

Second, make sure you using the temporary **user** token and not the **app** token.

**Comment by holms** [comment]
Sorry for not asking it there. Too used with github when it comes to issues.

So facebook api requires temporal token? Interesting. I've tried to use `get_app_access_token()` with my `app_id` and `app_secret`, and even with that generated token, when loaded class again with this generated token, it gives the same error. Would be nice to see some examples somewhere how to use this properly. I launch the application in daemon, I'd like to have a way of not changing token myself anywhere. Set it and for get it..

**Comment by martey** [comment]
A [discussion of the different types of access tokens](https://developers.facebook.com/docs/facebook-login/access-tokens) can be found in the Facebook documentation. @lucasrangit is right that you should be using a user token with `get_object("me")`.

I'm closing this since it isn't a bug, but you should post to the Google group if you have more trouble.
