### ISSUE TITLE
Version field is not present for GraphAPI object

### ISSUE THREAD

**Issue by heeren-cliqz** [pythonforfacebook/facebook-sdk#237]
I am using version facebook-sdk==0.4.0
And there is no 'version' field present.

graph = facebook.GraphAPI(access_token=token, version='2.4')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-347-c10ee7c7f1e5> in <module>()
----> 1 graph = facebook.GraphAPI(access_token=token, version='2.4')

TypeError: __init__() got an unexpected keyword argument 'version'

**Comment by martey** [comment]
facebook-sdk 0.4.0 was released in 2012, but [Facebook did not introduce API versioning until 2014](https://developers.facebook.com/blog/post/2014/04/30/the-new-facebook-login).

You can install the latest changes by doing

> `pip install git+https://github.com/pythonforfacebook/facebook-sdk#egg=facebook-sdk`
