### ISSUE TITLE
Unable to obtain email address for facebook user

### ISSUE THREAD

**Issue by karthikarun** [pythonforfacebook/facebook-sdk#246]
Hi,

I downloaded the python facebook sdk from the site https://pypi.python.org/pypi/facebook-sdk at the link https://pypi.python.org/packages/source/f/facebook-sdk/facebook-sdk-0.4.0.tar.gz

I followed the example for appengine from under examples/appengine. All works fine, except for that when I try to obtain the email address as 

profile = graph.get_object("me")
print profile['email']

It doesn't work as it throws a KeyError, since email isn't found in profile. 

(1) I am using a test login profile to login to the facebook account and I know for sure that this account has an email address and I gave permission to share the email address to the app when logging for the first time. 

(2) On the JavaScript SDK side, I am also passing "email" to the scope as shown below:
     scope="email,public_profile" 
in the fb:login-button scope.

which is what the facebook sdk docs suggests that I do to obtain email.

In spite of (1) and (2), still the profile obtained doesn't have the email address. Any idea what could be the root cause and the fix?

Thanks,
Karthik

**Comment by martey** [comment]
Instead of using version 0.4.0, try using a recent Git checkout.
