### ISSUE TITLE
Float required error

### ISSUE THREAD

**Issue by nbosco** [pythonforfacebook/facebook-sdk#250]
facebook.py", line 302, in request
    socket.setdefaulttimeout(self.timeout)
TypeError: a float is required

**Comment by martey** [comment]
`socket.setdefaulttimeout` isn't currently used in the code.

If you upgrade to a recent Git checkout, this should fix your issue.

**Comment by nbosco** [comment]
Is the most recent version 0.4.0? Because im getting it from https://pypi.python.org/pypi/facebook-sdk

**Comment by martey** [comment]
The most recent release is 0.4.0. There have been a lot of changes in the two years since it has been released, which is why I explicitly suggested you upgrade to a recent Git checkout.
