### ISSUE TITLE
Unable to pass parameters to get_object(s)

### ISSUE THREAD

**Issue by kbytesys** [pythonforfacebook/facebook-sdk#253]
The get_object(s) functions accept an **args parameter, but you pass it to the "args" of request function. This is bad because that array can't be used.

Atm if you use this code:

```
profile = graph.get_object('me', args={'fields': 'email,name'})
```

you will add only garbage into the request:

```
{'args': {'fields': 'email'}, 'access_token': 'myaccesstoken'}
```

Please accept this PR.

https://github.com/pythonforfacebook/facebook-sdk/pull/252

**Comment by martey** [comment]
FYI, you don't need to create an issue to alert me to a pull request. Closing & locking - further discussion should take place in #252.
