### ISSUE TITLE
Facebook search doesn't return verified user field in results

### ISSUE THREAD

**Issue by ShriramK** [pythonforfacebook/facebook-sdk#255]
As per 
http://stackoverflow.com/questions/31040445/facebook-graph-api-return-search-results-for-verified-accounts-only
can facebook search api call help specify is_verified  like

search?q=woody_allen&type=page&is_verified=true

to avoid making an additional call ?

**Comment by martey** [comment]
> can facebook search api call help specify is_verified ... to avoid making an additional call ?

Yes.

I'm not sure if this is a bug report or a support request. If you are looking for help with searching with Facebook, it would be better if you posted to [the Google Group](https://groups.google.com/forum/#!forum/pythonforfacebook).
