### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'version'

### ISSUE THREAD

**Issue by MonsieurCactus** [pythonforfacebook/facebook-sdk#256]
I am using Python 2.7 and I'm trying the Facebook SDK for the first time.  Using

   sudo pip install facebook-sdk

I was able to install a version of the Python Facebook library.  Using `pip show facebook-sdk | grep Version` I identified this as version `0.4.0`.  I tried a simple example from the [reference api](https://facebook-sdk.readthedocs.org/en/latest/api.html)

    import facebook
    graph = facebook.GraphAPI(access_token='your_token', version='2.2')

The Facebook [Graph Explorer](https://developers.facebook.com/tools/explorer/) online gives acess tokens.  The API versions now go up to the current version **2.5**.  Does **facebook-sdk** go that far yet?  In any case, the error message suggests there is no `version` keyword:

    TypeError: __init__() got an unexpected keyword argument 'version'

The code works without any `version` keyword.  Which one am I using then?

**Comment by EelaiWind** [comment]
you can install the latest version(**1.0.0.a0**) of facebook-sdk from source code on github (`python setup.py install`). Hope this would help!

**Comment by MonsieurCactus** [comment]
Cloned the Github repo and did `sudo python setup.py install`  - works like a charm:

    Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
    [GCC 4.8.2] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import facebook
    >>> token = '...'
    >>> graph = facebook.GraphAPI(access_token=token, version='2.5')
    >>> graph
    <facebook.GraphAPI object at 0x7f51f42126d0>
    >>> friends = graph.get_connections(id='me', connection_name='friends')
    >>> friends
    {u'paging': ..., u'data': ..., u'summary': {u'total_count': 50}}

**Comment by vabatta** [comment]
You should not have close this issue, as it's still giving this error (as pip package, not for the clone).

**Comment by Esyechka** [comment]
I cloned the Github repo and did `sudo python setup.py install` but now I'm getting `GraphAPIError: Invalid OAuth access token.
I don't have this problem with sudo pip install facebook-sdk, but then I can't get edge info.
Please help!
`

**Comment by martey** [comment]
@vabatta, this issue should remain closed, since it isn't a bug - version 0.4.0 never had API version support.

@Esyechka, your issue doesn't sound like the one described in this bug report. You should post an email with more details to [the Google Group](https://groups.google.com/forum/#!forum/pythonforfacebook).
