### ISSUE TITLE
PyPi version breaks for Python 3.5

### ISSUE THREAD

**Issue by masnun** [pythonforfacebook/facebook-sdk#272]
I installed the package from PyPi in my Python 3.5 virtualenv. I get the following error: 

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import facebook
  File "/Users/masnun/.virtualenvs/doubleshare/lib/python3.5/site-packages/facebook.py", line 222
    except urllib2.HTTPError, e:
                            ^
SyntaxError: invalid syntax
```

However, I installed the latest copy from Git and it worked fine. So I assume there's an older version pushed to PyPi which is broken on 3.5. I believe most people prefer PyPi to install a package. So it would be great to have a working version up there.

**Comment by martey** [comment]
Closing because this isn't an issue with current master and this is a duplicate (please search the issues before creating a new one). See #148, #192, and https://groups.google.com/forum/#!topic/pythonforfacebook/Xxj1u22yNXU.
