### ISSUE TITLE
UnicodeDecodeError when calling put_photo with an image generated with PIL

### ISSUE THREAD

**Issue by honi** [pythonforfacebook/facebook-sdk#43]
For some reason, images generated with PIL throw a UnicodeDecodeError when trying to upload to Facebook. 

Tested opening the image in Photoshop and saved as a new copy, and that image uploaded fine.

**Comment by martey** [comment]
I am pretty sure that this issue has been fixed by moving to requests (which involved significant changes to how `put_photo` works). Closing.
